/**
 ******************************************************************************
 * @file      startup_stm32f103rbtx.s
 * @author    Auto-generated by STM32CubeIDE
 * @brief     STM32F103RBTx device vector table for GCC toolchain.
 *            This module performs:
 *                - Set the initial SP
 *                - Set the initial PC == Reset_Handler,
 *                - Set the vector table entries with the exceptions ISR address
 *                - Branches to main in the C library (which eventually
 *                  calls main()).
 ******************************************************************************
 * @attention
 *
 * Copyright (c) ${year} STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

.syntax unified
.cpu cortex-m3
.fpu softvfp
.thumb

.include "stm32f10x.s"

.global g_pfnVectors
.global Default_Handler

/* start address for the initialization values of the .data section.
defined in linker script */
.word _sidata
/* start address for the .data section. defined in linker script */
.word _sdata
/* end address for the .data section. defined in linker script */
.word _edata
/* start address for the .bss section. defined in linker script */
.word _sbss
/* end address for the .bss section. defined in linker script */
.word _ebss

/**
 * @brief  This is the code that gets called when the processor first
 *          starts execution following a reset event. Only the absolutely
 *          necessary set is performed, after which the application
 *          supplied main() routine is called.
 * @param  None
 * @retval : None
*/

  .section .text.Reset_Handler
  .weak Reset_Handler
  .type Reset_Handler, %function


// требуется регистров: 3
// регистры: r0, r1, r2, r8
Reset_Handler:
	ldr		r0, =_estack
	mov		sp, r0          /* set stack pointer */


// инициализация порта С

	ldr		r0, =PERIPH_BB_BASE+ \
				(RCC_APB2ENR-PERIPH_BASE)*32 + \
				4*4						// запись адреса 4-го бита (для порта С) разрешения тактирования (bitbanding)
	mov		r1, #1						// запись "1" в регистр r1 для загрузки в r0
	str 	r1, [r0]					// загрузка значения из r1 в r0 для разрешения тактирования

	ldr		r0, =GPIOC_CRL				// запись адреса нижнего конфиг регистра порта С в r0
	ldr		r1, =0x33333333				// запись маски в r1: для PC0-PC7 - 00 11 (output 50MHz, general push-pull)
    str		r1, [r0]					// загрузка значения из r1 в r0 для настройки конфига


    ldr		r0, =GPIOC_CRH				// запись адреса верхнего конфиг регистра порта С в r0
	ldr		r1, =0x44					// запись маски в r1: для PC8-PC9 - 01 00 (input, analog)
	ldr		r2, [r0]					// считывание порта	в r2, потому что мы записываем только часть регистра и нам нужно сохранить значения, которые изначально были в конфиг регистре
    bfi		r2, r1, #0, #8				// копирование битов маски в позицию PIN8-9
    str		r2, [r0]					// загрузка результата в конфиг регистр порта

    mov		r0, #0						// обнуление регистра r0 (тест)
    mov		r8, #0						// запись в регистр r8 начального значения для вывода на семисегментник

loop:

	bl get_encoder_data					// получение данных от энкодера
	bl data_cmp							// вычисление стороны поворота и цифры для энкодера
	bl switch_digit						// вывод данных на семисегментник

	b loop


// требуется регистров: 3
// регистры: r9 (двоичный код сегментов для PC0-PC6),
//			 r8 (полученная цифра от энкодера),
//			 r1
switch_digit:

	tbb [PC, r8]			// поиск по таблице jump_table значения r8

jump_table:
    .byte (case_0 - jump_table)/2
    .byte (case_1 - jump_table)/2
    .byte (case_2 - jump_table)/2
    .byte (case_3 - jump_table)/2
    .byte (case_4 - jump_table)/2
    .byte (case_5 - jump_table)/2
    .byte (case_6 - jump_table)/2
    .byte (case_7 - jump_table)/2
    .byte (case_8 - jump_table)/2
    .byte (case_9 - jump_table)/2

case_0:
    ldr r9, =0x3F           // значения сегментов для "0"
    b set_segments
case_1:
    ldr r9, =0x06           // "1"
    b set_segments
case_2:
    ldr r9, =0x5B           // "2"
    b set_segments
case_3:
    ldr r9, =0x4F           // "3"
    b set_segments
case_4:
    ldr r9, =0x66           // "4"
    b set_segments
case_5:
    ldr r9, =0x6D           // "5"
    b set_segments
case_6:
    ldr r9, =0x7D           // "6"
    b set_segments
case_7:
    ldr r9, =0x07           // "7"
    b set_segments
case_8:
    ldr r9, =0x7F           // "8"
    b set_segments
case_9:
    ldr r9, =0x6F           // "9"
    b set_segments

set_segments:

	orr		r9, r9,	r10		// лог ИЛИ для вставки значения точки в полученное значение цифры

    ldr r1, =GPIOC_ODR      // получение адреса регистра вывода
    str r9, [r1]			// запись значений сегментов в регистр вывода
    bx lr


// требуется регистров: 3
// регистры: r0 (значения на энкодере: 0-ой б - тек dt, 1-ый б - предыд dt, 8-ой б - тек clk, 9-ый б - предыд clk),
//			 r1, r2 (было r5, r6)
// dt - PC8, clk - PC9
get_encoder_data:

	lsl		r0, r0, #1			// cдвиг регистра r0 на 1 бит влево для обновления предыд значений

	ldr		r1, =PERIPH_BB_BASE+ \
				(GPIOC_IDR-PERIPH_BASE)*32 + \
				8*4				// запись адреса 8-го бита регистра (текущее значение dt) входных данных (bitbanding)
	ldr		r2, [r1]			// получение значения PC8 в регистр r2
	bfi		r0, r2, #0, #1		// копирование текущего значения PC8 в r0 (можно было использовать просто маску (лог И с "1"), но так понятнее


	ldr		r1, =PERIPH_BB_BASE+ \
				(GPIOC_IDR-PERIPH_BASE)*32 + \
				9*4				// запись адреса 9-го бита регистра (текущее значение clk) входных данных (bitbanding)
	ldr		r2, [r1]			// получение значения PC9 в регистр r2
	bfi		r0, r2, #8, #1		// копирование текущего значения PC9 в r0

	bx lr


// требуется регистров: 5
// регистры: r0 (значения на энкодере: 0-ой б - тек dt, 1-ый б - предыд dt, 8-ой б - тек clk, 9-ый б - предыд clk),
// 			 r3 (временная копия r0)
//			 r4, r5, r6 (значения энкодера для сравнения между собой: r4 - предыд dt, r5 - тек dt, r6 - тек clk),
//			 r7 (хранит код направления поворота: 0 - на месте, 1 - право, 2 - лево),
//			 r8 (полученная цифра для энкодера)
data_cmp:

	mov		r3, r0				// создание копии значений из r0 в r3
	and		r5, r3, #1			// запись в r5 текущего значения dt
	lsr		r3, #1				// сдвиг вправо на 1 бит для получения предыд значения dt
	and		r4, r3, #1			// запись в r4 предыд значения dt

	mov		r7, #0				// установка helper-регистра для записи кода выполнения условий в "0"*/

	cmp		r4, r5				// сравнение предыд (r4) и тек (r5) значений dt
	it		ne					// условие: если "r4 != r5"
	bne		dt_changed			// то "значение dt изменилось - переход к подпрогр"


	bx lr


dt_changed:

	mov		r3, r0				// создание копии значений из r0 в r3
	lsr		r3, #8				// сдвиг вправо на 8 бит для получения тек значения clk
	and		r6, r3, #1			// запись в r5 текущего значения clk

	cmp		r5, r6				// сравнение тек dt (r5) и тек clk (r6) значений
	ite		eq					// условие если "r4 = r5"
	moveq	r7, #1				// code_right = 1
	movne	r7, #2				// code_left = 2

	cmp		r7, #1				// переход к продпрограмме увеличения цифры по коду из r7
	it		eq					// условие если "r7 = 1"
	beq		turn_right			// то переход к повороту вправо

	b		turn_left			// переход к повороту влево


turn_right:

	cmp		r8, #9				// проверка числа для энкодера на переполнение
	itte	lo					// условие если "r8 < 9"
	addlo	r8, r8, #1			// то: "добавить к числу 1"
	movlo	r10, #0				// то: "выставить в 0 регистр включения точки - точка будет выключена"
	movhs	r10, #1				// иначе: "выставить в 1 регистр включения точки - точка будет включена"

	lsl		r10, r10, #7		// сдвиг значения точки в 7 бит - бит точки в ODR регистре

	bx lr


turn_left:

	cmp		r8, #0				// проверка числа для энкодера на пустоту
	itte	hi					// условие если "r8 > 9"
	subhi	r8, r8, #1			// то: "вычесть 1"
	movhi	r10, #0				// то: "выставить в 0 регистр включения точки - точка будет выключена"
	movls	r10, #1				// иначе: "выставить в 1 регистр включения точки - точка будет включена"

	lsl		r10, r10, #7	// сдвиг значения точки в 7 бит - бит точки в ODR регистре

	bx lr



  .size Reset_Handler, .-Reset_Handler

/**
 * @brief  This is the code that gets called when the processor receives an
 *         unexpected interrupt.  This simply enters an infinite loop, preserving
 *         the system state for examination by a debugger.
 *
 * @param  None
 * @retval : None
*/
  .section .text.Default_Handler,"ax",%progbits
Default_Handler:
Infinite_Loop:
  b Infinite_Loop
  .size Default_Handler, .-Default_Handler

/******************************************************************************
*
* The STM32F103RBTx vector table.  Note that the proper constructs
* must be placed on this to ensure that it ends up at physical address
* 0x0000.0000.
*
******************************************************************************/
  .section .isr_vector,"a",%progbits
  .type g_pfnVectors, %object
  .size g_pfnVectors, .-g_pfnVectors

g_pfnVectors:
  .word _estack
  .word Reset_Handler
  .word NMI_Handler
  .word HardFault_Handler
  .word	MemManage_Handler
  .word	BusFault_Handler
  .word	UsageFault_Handler
  .word	0
  .word	0
  .word	0
  .word	0
  .word	SVC_Handler
  .word	DebugMon_Handler
  .word	0
  .word	PendSV_Handler
  .word	SysTick_Handler
  .word	WWDG_IRQHandler           			/* Window Watchdog interrupt                        */
  .word	PVD_IRQHandler            			/* PVD through EXTI line detection interrupt        */
  .word	TAMPER_IRQHandler         			/* Tamper interrupt                                 */
  .word	RTC_IRQHandler            			/* RTC global interrupt                             */
  .word	FLASH_IRQHandler          			/* Flash global interrupt                           */
  .word	RCC_IRQHandler            			/* RCC global interrupt                             */
  .word	EXTI0_IRQHandler          			/* EXTI Line0 interrupt                             */
  .word	EXTI1_IRQHandler          			/* EXTI Line1 interrupt                             */
  .word	EXTI2_IRQHandler          			/* EXTI Line2 interrupt                             */
  .word	EXTI3_IRQHandler          			/* EXTI Line3 interrupt                             */
  .word	EXTI4_IRQHandler          			/* EXTI Line4 interrupt                             */
  .word	DMA1_Channel1_IRQHandler  			/* DMA1 Channel1 global interrupt                   */
  .word	DMA1_Channel2_IRQHandler  			/* DMA1 Channel2 global interrupt                   */
  .word	DMA1_Channel3_IRQHandler  			/* DMA1 Channel3 global interrupt                   */
  .word	DMA1_Channel4_IRQHandler  			/* DMA1 Channel4 global interrupt                   */
  .word	DMA1_Channel5_IRQHandler  			/* DMA1 Channel5 global interrupt                   */
  .word	DMA1_Channel6_IRQHandler  			/* DMA1 Channel6 global interrupt                   */
  .word	DMA1_Channel7_IRQHandler  			/* DMA1 Channel7 global interrupt                   */
  .word	ADC1_2_IRQHandler         			/* ADC1 and ADC2 global interrupt                   */
  .word	USB_HP_CAN_TX_IRQHandler  			/* USB High Priority or CAN TX interrupts           */
  .word	USB_LP_CAN_RX0_IRQHandler 			/* USB Low Priority or CAN RX0 interrupts           */
  .word	CAN_RX1_IRQHandler        			/* CAN RX1 interrupt                                */
  .word	CAN_SCE_IRQHandler        			/* CAN SCE interrupt                                */
  .word	EXTI9_5_IRQHandler        			/* EXTI Line[9:5] interrupts                        */
  .word	TIM1_BRK_IRQHandler       			/* TIM1 Break interrupt                             */
  .word	TIM1_UP_IRQHandler        			/* TIM1 Update interrupt                            */
  .word	TIM1_TRG_COM_IRQHandler   			/* TIM1 Trigger and Commutation interrupts          */
  .word	TIM1_CC_IRQHandler        			/* TIM1 Capture Compare interrupt                   */
  .word	TIM2_IRQHandler           			/* TIM2 global interrupt                            */
  .word	TIM3_IRQHandler           			/* TIM3 global interrupt                            */
  .word	TIM4_IRQHandler           			/* TIM4 global interrupt                            */
  .word	I2C1_EV_IRQHandler        			/* I2C1 event interrupt                             */
  .word	I2C1_ER_IRQHandler        			/* I2C1 error interrupt                             */
  .word	I2C2_EV_IRQHandler        			/* I2C2 event interrupt                             */
  .word	I2C2_ER_IRQHandler        			/* I2C2 error interrupt                             */
  .word	SPI1_IRQHandler           			/* SPI1 global interrupt                            */
  .word	SPI2_IRQHandler           			/* SPI2 global interrupt                            */
  .word	USART1_IRQHandler         			/* USART1 global interrupt                          */
  .word	USART2_IRQHandler         			/* USART2 global interrupt                          */
  .word	USART3_IRQHandler         			/* USART3 global interrupt                          */
  .word	EXTI15_10_IRQHandler      			/* EXTI Line[15:10] interrupts                      */
  .word	RTCAlarm_IRQHandler       			/* RTC Alarms through EXTI line interrupt           */
  .word	0                         			/* Reserved                                         */
  .word	TIM8_BRK_IRQHandler       			/* TIM8 Break interrupt                             */
  .word	TIM8_UP_IRQHandler        			/* TIM8 Update interrupt                            */
  .word	TIM8_TRG_COM_IRQHandler   			/* TIM8 Trigger and Commutation interrupts          */
  .word	TIM8_CC_IRQHandler        			/* TIM8 Capture Compare interrupt                   */
  .word	ADC3_IRQHandler           			/* ADC3 global interrupt                            */
  .word	FSMC_IRQHandler           			/* FSMC global interrupt                            */
  .word	SDIO_IRQHandler           			/* SDIO global interrupt                            */
  .word	TIM5_IRQHandler           			/* TIM5 global interrupt                            */
  .word	SPI3_IRQHandler           			/* SPI3 global interrupt                            */
  .word	UART4_IRQHandler          			/* UART4 global interrupt                           */
  .word	UART5_IRQHandler          			/* UART5 global interrupt                           */
  .word	TIM6_IRQHandler           			/* TIM6 global interrupt                            */
  .word	TIM7_IRQHandler           			/* TIM7 global interrupt                            */
  .word	DMA2_Channel1_IRQHandler  			/* DMA2 Channel1 global interrupt                   */
  .word	DMA2_Channel2_IRQHandler  			/* DMA2 Channel2 global interrupt                   */
  .word	DMA2_Channel3_IRQHandler  			/* DMA2 Channel3 global interrupt                   */
  .word	DMA2_Channel4_5_IRQHandler			/* DMA2 Channel4 and DMA2 Channel5 global interrupt */

/*******************************************************************************
*
* Provide weak aliases for each Exception handler to the Default_Handler.
* As they are weak aliases, any function with the same name will override
* this definition.
*
*******************************************************************************/

	.weak	NMI_Handler
	.thumb_set NMI_Handler,Default_Handler

	.weak	HardFault_Handler
	.thumb_set HardFault_Handler,Default_Handler

	.weak	MemManage_Handler
	.thumb_set MemManage_Handler,Default_Handler

	.weak	BusFault_Handler
	.thumb_set BusFault_Handler,Default_Handler

	.weak	UsageFault_Handler
	.thumb_set UsageFault_Handler,Default_Handler

	.weak	SVC_Handler
	.thumb_set SVC_Handler,Default_Handler

	.weak	DebugMon_Handler
	.thumb_set DebugMon_Handler,Default_Handler

	.weak	PendSV_Handler
	.thumb_set PendSV_Handler,Default_Handler

	.weak	SysTick_Handler
	.thumb_set SysTick_Handler,Default_Handler

	.weak	WWDG_IRQHandler
	.thumb_set WWDG_IRQHandler,Default_Handler

	.weak	PVD_IRQHandler
	.thumb_set PVD_IRQHandler,Default_Handler

	.weak	TAMPER_IRQHandler
	.thumb_set TAMPER_IRQHandler,Default_Handler

	.weak	RTC_IRQHandler
	.thumb_set RTC_IRQHandler,Default_Handler

	.weak	FLASH_IRQHandler
	.thumb_set FLASH_IRQHandler,Default_Handler

	.weak	RCC_IRQHandler
	.thumb_set RCC_IRQHandler,Default_Handler

	.weak	EXTI0_IRQHandler
	.thumb_set EXTI0_IRQHandler,Default_Handler

	.weak	EXTI1_IRQHandler
	.thumb_set EXTI1_IRQHandler,Default_Handler

	.weak	EXTI2_IRQHandler
	.thumb_set EXTI2_IRQHandler,Default_Handler

	.weak	EXTI3_IRQHandler
	.thumb_set EXTI3_IRQHandler,Default_Handler

	.weak	EXTI4_IRQHandler
	.thumb_set EXTI4_IRQHandler,Default_Handler

	.weak	DMA1_Channel1_IRQHandler
	.thumb_set DMA1_Channel1_IRQHandler,Default_Handler

	.weak	DMA1_Channel2_IRQHandler
	.thumb_set DMA1_Channel2_IRQHandler,Default_Handler

	.weak	DMA1_Channel3_IRQHandler
	.thumb_set DMA1_Channel3_IRQHandler,Default_Handler

	.weak	DMA1_Channel4_IRQHandler
	.thumb_set DMA1_Channel4_IRQHandler,Default_Handler

	.weak	DMA1_Channel5_IRQHandler
	.thumb_set DMA1_Channel5_IRQHandler,Default_Handler

	.weak	DMA1_Channel6_IRQHandler
	.thumb_set DMA1_Channel6_IRQHandler,Default_Handler

	.weak	DMA1_Channel7_IRQHandler
	.thumb_set DMA1_Channel7_IRQHandler,Default_Handler

	.weak	ADC1_2_IRQHandler
	.thumb_set ADC1_2_IRQHandler,Default_Handler

	.weak	USB_HP_CAN_TX_IRQHandler
	.thumb_set USB_HP_CAN_TX_IRQHandler,Default_Handler

	.weak	USB_LP_CAN_RX0_IRQHandler
	.thumb_set USB_LP_CAN_RX0_IRQHandler,Default_Handler

	.weak	CAN_RX1_IRQHandler
	.thumb_set CAN_RX1_IRQHandler,Default_Handler

	.weak	CAN_SCE_IRQHandler
	.thumb_set CAN_SCE_IRQHandler,Default_Handler

	.weak	EXTI9_5_IRQHandler
	.thumb_set EXTI9_5_IRQHandler,Default_Handler

	.weak	TIM1_BRK_IRQHandler
	.thumb_set TIM1_BRK_IRQHandler,Default_Handler

	.weak	TIM1_UP_IRQHandler
	.thumb_set TIM1_UP_IRQHandler,Default_Handler

	.weak	TIM1_TRG_COM_IRQHandler
	.thumb_set TIM1_TRG_COM_IRQHandler,Default_Handler

	.weak	TIM1_CC_IRQHandler
	.thumb_set TIM1_CC_IRQHandler,Default_Handler

	.weak	TIM2_IRQHandler
	.thumb_set TIM2_IRQHandler,Default_Handler

	.weak	TIM3_IRQHandler
	.thumb_set TIM3_IRQHandler,Default_Handler

	.weak	TIM4_IRQHandler
	.thumb_set TIM4_IRQHandler,Default_Handler

	.weak	I2C1_EV_IRQHandler
	.thumb_set I2C1_EV_IRQHandler,Default_Handler

	.weak	I2C1_ER_IRQHandler
	.thumb_set I2C1_ER_IRQHandler,Default_Handler

	.weak	I2C2_EV_IRQHandler
	.thumb_set I2C2_EV_IRQHandler,Default_Handler

	.weak	I2C2_ER_IRQHandler
	.thumb_set I2C2_ER_IRQHandler,Default_Handler

	.weak	SPI1_IRQHandler
	.thumb_set SPI1_IRQHandler,Default_Handler

	.weak	SPI2_IRQHandler
	.thumb_set SPI2_IRQHandler,Default_Handler

	.weak	USART1_IRQHandler
	.thumb_set USART1_IRQHandler,Default_Handler

	.weak	USART2_IRQHandler
	.thumb_set USART2_IRQHandler,Default_Handler

	.weak	USART3_IRQHandler
	.thumb_set USART3_IRQHandler,Default_Handler

	.weak	EXTI15_10_IRQHandler
	.thumb_set EXTI15_10_IRQHandler,Default_Handler

	.weak	RTCAlarm_IRQHandler
	.thumb_set RTCAlarm_IRQHandler,Default_Handler

	.weak	TIM8_BRK_IRQHandler
	.thumb_set TIM8_BRK_IRQHandler,Default_Handler

	.weak	TIM8_UP_IRQHandler
	.thumb_set TIM8_UP_IRQHandler,Default_Handler

	.weak	TIM8_TRG_COM_IRQHandler
	.thumb_set TIM8_TRG_COM_IRQHandler,Default_Handler

	.weak	TIM8_CC_IRQHandler
	.thumb_set TIM8_CC_IRQHandler,Default_Handler

	.weak	ADC3_IRQHandler
	.thumb_set ADC3_IRQHandler,Default_Handler

	.weak	FSMC_IRQHandler
	.thumb_set FSMC_IRQHandler,Default_Handler

	.weak	SDIO_IRQHandler
	.thumb_set SDIO_IRQHandler,Default_Handler

	.weak	TIM5_IRQHandler
	.thumb_set TIM5_IRQHandler,Default_Handler

	.weak	SPI3_IRQHandler
	.thumb_set SPI3_IRQHandler,Default_Handler

	.weak	UART4_IRQHandler
	.thumb_set UART4_IRQHandler,Default_Handler

	.weak	UART5_IRQHandler
	.thumb_set UART5_IRQHandler,Default_Handler

	.weak	TIM6_IRQHandler
	.thumb_set TIM6_IRQHandler,Default_Handler

	.weak	TIM7_IRQHandler
	.thumb_set TIM7_IRQHandler,Default_Handler

	.weak	DMA2_Channel1_IRQHandler
	.thumb_set DMA2_Channel1_IRQHandler,Default_Handler

	.weak	DMA2_Channel2_IRQHandler
	.thumb_set DMA2_Channel2_IRQHandler,Default_Handler

	.weak	DMA2_Channel3_IRQHandler
	.thumb_set DMA2_Channel3_IRQHandler,Default_Handler

	.weak	DMA2_Channel4_5_IRQHandler
	.thumb_set DMA2_Channel4_5_IRQHandler,Default_Handler

	.weak	SystemInit

/************************ (C) COPYRIGHT STMicroelectonics *****END OF FILE****/
